# Generated by Django 5.0.4 on 2024-04-07 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('address', models.TextField()),
                ('disk_space', models.IntegerField()),
                ('memory_space', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docker_image_link', models.CharField(max_length=200)),
                ('docker_container_link', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('cores', models.IntegerField()),
                ('port', models.IntegerField()),
                ('disk_space', models.IntegerField()),
                ('memory_space', models.IntegerField()),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.hosting')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user_rent_docker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.container')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'container'],
            },
        ),
    ]
