# Generated by Django 5.0.4 on 2024-05-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_container_is_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.hosting')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
