# Generated by Django 5.0.4 on 2024-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_containerconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerconfig',
            old_name='cpu',
            new_name='cores',
        ),
        migrations.RenameField(
            model_name='containerconfig',
            old_name='disk',
            new_name='disk_space',
        ),
        migrations.RenameField(
            model_name='containerconfig',
            old_name='ram',
            new_name='memory_space',
        ),
        migrations.AddField(
            model_name='containerconfig',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
