# Generated by Django 5.0.4 on 2024-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_rename_cpu_containerconfig_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
