# Generated by Django 5.0.4 on 2024-06-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_containerlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlogs',
            name='container',
            field=models.CharField(max_length=300),
        ),
    ]
